[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"

[dependencies]
priority-queue = "2.1.1"
aoc-utils-crate = { git = "https://github.com/maxwen/aoc-utils-crate" }

[profile.release]
opt-level = 3
codegen-units = 1
lto = false